### ISSUE TITLE
insure current docker install

### ISSUE THREAD

**Issue by liljenstolpe** [Metaswitch/calico-docker-prototype#1]
We use the --restart flag in docker run (I don't know what else may be dependent on newer versions of docker), but this will not work in an ubuntu 14.04 install using apt-get install docker.io.  It installs docker 1.0.1.  

You must use the alternate installation instructions found https://docs.docker.com/installation/ubuntulinux/ under the section Docker-maintained Package Installation

**Comment by plwhite** [comment]
Fixed in pull #10. Actually, just documenting the required version, but that should be enough.
