### ISSUE TITLE
sed doesn't do variable substitution

### ISSUE THREAD

**Issue by liljenstolpe** [Metaswitch/calico-docker-prototype#11]
The current sed script replaces IP1 with $IP1, not the value of $IP1.  Fix is to replace the ' with a ".  Pull request with the fixed doc submitted

**Comment by liljenstolpe** [comment]
I've also fixed a missed (as root) for one of the commands.

**Comment by neiljerram** [comment]
Sorry, I missed that sed mistake because I did the IP substitutions by hand.  Your fix sounds right to me.

------------------

**Comment by plwhite** [comment]
Fixed.
