### ISSUE TITLE
network_container.sh is broken

### ISSUE THREAD

**Issue by liljenstolpe** [Metaswitch/calico-docker-prototype#5]
$ sudo sh /opt/demo/network_container.sh 7ef424adbdaa 10.192.1.1 1
Networking an endpoint with container ID 7ef424adbdaa and address 10.192.1.1
/opt/demo/network_container.sh: 32: /opt/demo/network_container.sh: Bad substitution

**Comment by liljenstolpe** [comment]
I didn't have time to diagnose right now.

**Comment by plwhite** [comment]
You are calling network_container with too few arguments - so I'd expect it not to work. However, this is firewalled at line 20. Similarly, I cannot make line 32 generate that error in bash, but I can in sh.

I wonder if somehow on your server sh does not map to bash, and for some reason the "#!/bin/bash" is not working?

Can you try :

* verifying that you are running the latest code (though I am sure you are)
* explicitly running using bash, not sh (though it should not make a difference)
* if neither of those helps, drop me a mail with server details and I'll take a look myself

**Comment by liljenstolpe** [comment]
Ok - two issues:

1) The script is not executable - since it ends in a .sh, I used the following command to execute it:
$ /bin/sh network_container.sh <CID> <IP> <GROUP>

That was the error.  We could either end it with bash (so people will fire it off with bash) or, better, ship it as an executable script.  Then people will just run it, rather than pass it to a shell.  Evidently /bin/sh does not, in turn, call bash, even if #!/bin/bash is in the first line (or it calls bash in some form of bourne shell emulation mode).

2) The script needs to be called as root (like the others, but it's not noted, and the error thrown is:
Get http:///var/run/docker.sock/v1.16/images/7ef424adbdaa/json: dial unix /var/run/docker.sock: permission denied. Are you trying to connect to a TLS-enabled daemon without TLS?cdl@docker-0:/opt/demo$ . network_container.sh 7ef424adbdaa 10.192.1.1. 1

The permission denied is the key, but the TLS enabled daemon will throw folks off.

**Comment by plwhite** [comment]
Weirdly, I cannot repro the first problem at all. If I run it using /bin/sh on either CoreOS or Ubuntu, it correctly switches to bash; that might be something to do with the environment. However, no harm in changing the instructions (and firewalling somehow perhaps). I didn't make it executable since the executable bit might have got lost on the way.

As for the second, we should document the whole "running as root" thing more consistently, and I should add a test to the script that bombs out if not run as root.

**Comment by plwhite** [comment]
Fixed in pull #10. Actually, we just document to run with bash, but I think that is enough to fix whatever oddity was happening.
